### ISSUE TITLE
Cannot find base config file "@tsconfig/svelte/tsconfig.json"

### ISSUE THREAD

**Issue by ChrisLMerrill** [kyle-n/WebExtensionTemplate#5]
Working in the React branch, I immediately encounter this error in build:

> Cannot find base config file "@tsconfig/svelte/tsconfig.json"

I noticed that tsconfig.json references svelte on lined 3:
` "extends": "@tsconfig/svelte/tsconfig.json", `
and 17:
`     "types": ["svelte"] `

My JS experience is admittedly a little on the light side. What am I missing?   TIA!

**Comment by kyle-n** [comment]
Hi, Chris. I just missed that when I created the React branch. Thanks for flagging this! Fixed with ce242c1

**Comment by ChrisLMerrill** [comment]
Thanks!
